server {
    listen 80;

    # 1. 프론트엔드 (Vite/React) 연결
    location / {
        proxy_pass http://project_frontend:5173; # yml에 정의한 서비스명
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 2. 백엔드 (Node.js) API 연결
    # 프론트에서 호출하는 /api 주소를 백엔드 포트로 전달
    location /api/ {
        proxy_pass http://project_backend:5000; # 백엔드 컨테이너 포트 (5000)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}